# Generated by Django 6.0.7 on 2026-08-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_activity_date',
            field=models.DateField(blank=True, null=True, verbose_name='Последняя активность'),
        ),
        migrations.AddField(
            model_name='user',
            name='streak',
            field=models.IntegerField(default=0, verbose_name='Серия дней'),
        ),
    ]
