# Generated by Django 6.0.7 on 2026-08-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_api', '0004_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='last_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
