# Generated by Django 6.0.7 on 2026-08-29 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_api', '0006_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('vk', 'VK'), ('telegram', 'Telegram'), ('site', 'Сайт')], max_length=20)),
                ('text', models.TextField()),
                ('publish_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('scheduled', 'Запланирован'), ('published', 'Опубликован')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['publish_date'],
            },
        ),
    ]
