# Generated by Django 5.2.17 on 2026-09-01 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot_api", "0007_post"),
    ]

    operations = [
        migrations.CreateModel(
            name="Channel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("vk", "VK"),
                            ("telegram", "Telegram"),
                            ("max", "MAX"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Человекочитаемое имя, например «Основная группа ВК»",
                        max_length=100,
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        help_text="ID группы/канала. Для VK — числовой ID сообщества (без минуса), из vk.com/club<ID> или vk.com/id_community.",
                        max_length=100,
                    ),
                ),
                (
                    "access_token",
                    models.CharField(
                        blank=True,
                        help_text="Токен доступа для публикации (для VK — токен сообщества с правом 'wall', из Управление сообществом → Работа с API → Ключи доступа).",
                        max_length=255,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["platform", "name"],
            },
        ),
        migrations.AlterField(
            model_name="post",
            name="platform",
            field=models.CharField(
                blank=True,
                help_text="Устаревшее поле, не используется в новых постах.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Черновик"),
                    ("scheduled", "Запланирован"),
                    ("published", "Опубликован"),
                    ("failed", "Ошибка публикации"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="PostChannelStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Запланирован"),
                            ("published", "Опубликован"),
                            ("failed", "Ошибка"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "external_post_id",
                    models.CharField(
                        blank=True,
                        help_text="ID опубликованного поста в самой платформе (для ссылки).",
                        max_length=100,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_statuses",
                        to="bot_api.channel",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channel_statuses",
                        to="bot_api.post",
                    ),
                ),
            ],
            options={
                "unique_together": {("post", "channel")},
            },
        ),
        migrations.AddField(
            model_name="post",
            name="channels",
            field=models.ManyToManyField(
                blank=True,
                related_name="posts",
                through="bot_api.PostChannelStatus",
                to="bot_api.channel",
            ),
        ),
    ]
