# Generated by Django 6.0.7 on 2026-07-29 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_product_delete_products_alter_student_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
