# Generated by Django 6.0.7 on 2026-07-30 19:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_delete_student'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoTriggerCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_phrase', models.CharField(max_length=200)),
                ('new_phrase', models.CharField(max_length=200)),
                ('node_type', models.CharField(blank=True, max_length=100, null=True)),
                ('count', models.PositiveIntegerField(default=0)),
                ('post_suppression_count', models.PositiveIntegerField(default=0)),
                ('sample_data', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('suppressed', 'Suppressed'), ('active', 'Active')], default='pending', max_length=20)),
                ('rejection_count', models.PositiveIntegerField(default=0)),
                ('last_rejected_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Сообщение')),
                ('is_public', models.BooleanField(default=True, verbose_name='Публичное')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClarificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('sent', 'Отправлен'), ('in_progress', 'В работе'), ('resolved', 'Закрыт')], default='draft', max_length=20)),
                ('message', models.TextField(verbose_name='Текст запроса')),
                ('resolution_summary', models.TextField(blank=True, verbose_name='Ответ куратора')),
                ('snapshot_data', models.JSONField(blank=True, null=True, verbose_name='Снапшот данных')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(unique=True)),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Подзаголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('experienced', 'Experienced'), ('observer', 'Observer')], default='beginner', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='courses/', verbose_name='Изображение')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена')),
                ('is_free', models.BooleanField(default=False, verbose_name='Бесплатный')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликован')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Иконка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Категория курсов',
                'verbose_name_plural': 'Категории курсов',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackNodeLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('strengths', 'Сильные стороны'), ('shadows', 'Тени'), ('to_check', 'Что проверить')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ForumCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Категория форума',
                'verbose_name_plural': 'Категории форума',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ForumPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ForumThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок темы')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Закреплена')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Закрыта')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('number', models.PositiveIntegerField(verbose_name='Номер урока')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на видео')),
                ('duration', models.PositiveIntegerField(default=0, verbose_name='Длительность (мин)')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='MapEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edge_type', models.CharField(choices=[('explains', 'Explains'), ('contradicts', 'Contradicts'), ('illustrates', 'Illustrates'), ('follows_from', 'Follows_from'), ('possible_substitution', 'Possible_substitution')], default='explains', max_length=30, verbose_name='Тип связи')),
                ('reason', models.TextField(blank=True, verbose_name='Пояснение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MapNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=150, verbose_name='Метка узла')),
                ('content', models.TextField(blank=True, verbose_name='Содержание узла')),
                ('node_type', models.CharField(choices=[('fact', 'Fact'), ('interpretation', 'Interpretation'), ('bias', 'Bias'), ('check', 'Check'), ('forum_thread', 'Forum_thread'), ('chat_message', 'Chat_message'), ('summary', 'Summary')], default='fact', max_length=30, verbose_name='Тип узла')),
                ('order', models.PositiveIntegerField(default=0)),
                ('review_status', models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Одобрено'), ('needs_rework', 'На доработке'), ('excellent', 'Отлично'), ('possible_substitution', 'Возможная подмена')], default='pending', max_length=30, verbose_name='Статус проверки')),
                ('risk_type', models.CharField(choices=[('none', 'Нет риска'), ('possible_substitution', 'Возможная подмена понятий'), ('weak_argument', 'Слабая аргументация'), ('no_example', 'Нет примера'), ('ambiguous', 'Двусмысленность')], default='none', max_length=50, verbose_name='Тип риска')),
                ('weight', models.FloatField(default=0, verbose_name='Вес')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MapNodeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=150)),
                ('content', models.TextField(blank=True)),
                ('node_type', models.CharField(max_length=30)),
                ('review_status', models.CharField(max_length=30)),
                ('risk_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False, verbose_name='Активная версия')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название модуля')),
                ('number', models.PositiveIntegerField(verbose_name='Номер модуля')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_required', models.BooleanField(default=True, verbose_name='Обязательный')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='ObservationMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название карты')),
                ('central_node', models.CharField(max_length=200, verbose_name='Центральный узел')),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('experienced', 'Experienced'), ('observer', 'Observer')], default='beginner', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('experienced', 'Experienced'), ('observer', 'Observer')], default='beginner', max_length=20)),
                ('bio', models.TextField(blank=True, verbose_name='О себе')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар')),
                ('last_seen_feedback_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RejectedTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_phrase', models.CharField(max_length=200)),
                ('new_phrase', models.CharField(max_length=200)),
                ('node_type', models.CharField(blank=True, max_length=100, null=True)),
                ('rejection_count', models.PositiveIntegerField(default=0)),
                ('last_rejected_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_strengths', models.TextField(blank=True, verbose_name='Комментарий по сильным сторонам')),
                ('feedback_shadows', models.TextField(blank=True, verbose_name='Комментарий по теням')),
                ('feedback_to_check', models.TextField(blank=True, verbose_name='Что проверить')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seminar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Номер семинара')),
                ('title', models.CharField(max_length=250, verbose_name='Тема семинара')),
                ('date', models.DateTimeField(verbose_name='Дата и время')),
                ('description', models.TextField(blank=True, verbose_name='Описание/задание')),
                ('material_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на материалы')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на видео')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Проведён')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='SeminarGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название группы')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('min_participants', models.PositiveIntegerField(default=3, verbose_name='Минимум участников')),
                ('start_date', models.DateField(verbose_name='Дата старта')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('is_full', models.BooleanField(default=False, verbose_name='Набрана')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeminarSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact', models.TextField(verbose_name='Факт, который я заметил')),
                ('interpretation', models.TextField(verbose_name='Моя интерпретация')),
                ('possible_bias', models.TextField(blank=True, verbose_name='Возможное искажение')),
                ('is_submitted', models.BooleanField(default=False, verbose_name='Сдано')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('review_status', models.CharField(choices=[('pending', 'Ожидает проверки'), ('approved', 'Принято'), ('needs_clarification', 'Нужно уточнение'), ('rejected', 'Требует переработки')], default='pending', max_length=30)),
                ('review_comment', models.TextField(blank=True, verbose_name='Комментарий ведущего')),
                ('needs_personal_review', models.BooleanField(default=False, verbose_name='Требует личной проработки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TriggerApprovalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approve', 'Одобрено'), ('reject', 'Отклонено')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TriggerRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_phrase', models.CharField(max_length=200)),
                ('new_phrase', models.CharField(max_length=200)),
                ('node_type', models.CharField(blank=True, max_length=100, null=True)),
                ('count', models.PositiveIntegerField(default=0)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('sample_node_ids', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddIndex(
            model_name='autotriggercandidate',
            index=models.Index(fields=['status', 'expires_at'], name='main_autotr_status_30f5f9_idx'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='parent_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='main.chatmessage'),
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='main.coursecategory'),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='parent_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='main.forumpost'),
        ),
        migrations.AddField(
            model_name='forumthread',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_threads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='forumthread',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='main.forumcategory'),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='main.forumthread'),
        ),
        migrations.AddField(
            model_name='mapnode',
            name='parent_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='main.mapnode'),
        ),
        migrations.AddField(
            model_name='mapedge',
            name='source_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='main.mapnode'),
        ),
        migrations.AddField(
            model_name='mapedge',
            name='target_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='main.mapnode'),
        ),
        migrations.AddField(
            model_name='feedbacknodelink',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_links', to='main.mapnode'),
        ),
        migrations.AddField(
            model_name='clarificationrequest',
            name='resolved_nodes',
            field=models.ManyToManyField(blank=True, related_name='clarified_in', to='main.mapnode'),
        ),
        migrations.AddField(
            model_name='mapnodeversion',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='main.mapnode'),
        ),
        migrations.AddField(
            model_name='module',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='main.course'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='main.module'),
        ),
        migrations.AddField(
            model_name='observationmap',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mapnode',
            name='map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='main.observationmap'),
        ),
        migrations.AddField(
            model_name='participation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rejectedtrigger',
            name='rejected_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedbacknodelink',
            name='feedback',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_links', to='main.reviewfeedback'),
        ),
        migrations.AddField(
            model_name='clarificationrequest',
            name='feedback',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clarification_requests', to='main.reviewfeedback'),
        ),
        migrations.AddField(
            model_name='participation',
            name='completed_seminars',
            field=models.ManyToManyField(blank=True, related_name='completed_by', to='main.seminar'),
        ),
        migrations.AddField(
            model_name='mapnode',
            name='source_seminar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.seminar'),
        ),
        migrations.AddField(
            model_name='seminargroup',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seminar_groups', to='main.course'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seminars', to='main.seminargroup'),
        ),
        migrations.AddField(
            model_name='participation',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='main.seminargroup'),
        ),
        migrations.AddField(
            model_name='seminarsubmission',
            name='seminar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='main.seminar'),
        ),
        migrations.AddField(
            model_name='seminarsubmission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewfeedback',
            name='submission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='main.seminarsubmission'),
        ),
        migrations.AddField(
            model_name='triggerapprovallog',
            name='candidate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.autotriggercandidate'),
        ),
        migrations.AddField(
            model_name='triggerapprovallog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='triggerrule',
            unique_together={('old_phrase', 'new_phrase', 'node_type')},
        ),
        migrations.AddField(
            model_name='triggerapprovallog',
            name='rule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.triggerrule'),
        ),
        migrations.AlterUniqueTogether(
            name='mapedge',
            unique_together={('source_node', 'target_node')},
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('course', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('module', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='rejectedtrigger',
            unique_together={('old_phrase', 'new_phrase', 'node_type')},
        ),
        migrations.AlterUniqueTogether(
            name='seminar',
            unique_together={('group', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='participation',
            unique_together={('user', 'group')},
        ),
        migrations.AlterUniqueTogether(
            name='seminarsubmission',
            unique_together={('user', 'seminar')},
        ),
    ]
