# Generated by Django 6.0.7 on 2026-08-21 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='Номер модуля')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='Подзаголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('content', models.TextField(blank=True, verbose_name='Содержание лекции')),
                ('position_x', models.FloatField(default=0, verbose_name='Позиция X в 3D')),
                ('position_z', models.FloatField(default=0, verbose_name='Позиция Z в 3D')),
                ('color', models.CharField(default='#6cbfff', max_length=7, verbose_name='Цвет в 3D')),
                ('key_concepts', models.JSONField(default=list, verbose_name='Ключевые понятия')),
                ('duration', models.PositiveIntegerField(default=30, verbose_name='Длительность (мин)')),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Модуль',
                'verbose_name_plural': 'Модули курса',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='GameAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_name', models.CharField(max_length=100, verbose_name='Объект')),
                ('association', models.TextField(verbose_name='Ассоциация')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_associations', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associations', to='myapp.module')),
            ],
            options={
                'verbose_name': 'Ассоциация',
                'verbose_name_plural': 'Ассоциации',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserCourseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_modules', models.ManyToManyField(blank=True, related_name='completed_by', to='myapp.module')),
                ('current_module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_at', to='myapp.module')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='course_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Прогресс пользователя',
                'verbose_name_plural': 'Прогресс пользователей',
            },
        ),
    ]
