# Generated by Django 6.0.7 on 2026-08-25 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_module_gameassociation_usercourseprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='associations',
            field=models.JSONField(default=list, verbose_name='Ассоциации'),
        ),
        migrations.AlterField(
            model_name='gameassociation',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_associations', to='myapp.module'),
        ),
        migrations.CreateModel(
            name='UserStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.IntegerField(default=0, verbose_name='Текущая серия')),
                ('max_streak', models.IntegerField(default=0, verbose_name='Максимальная серия')),
                ('last_activity', models.DateField(blank=True, null=True, verbose_name='Последняя активность')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Серия пользователя',
                'verbose_name_plural': 'Серии пользователей',
            },
        ),
    ]
