# Generated by Django 6.0.7 on 2026-08-25 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_module_associations_alter_gameassociation_module_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='allow_comments',
            field=models.BooleanField(default=True, verbose_name='Разрешить комментарии'),
        ),
        migrations.AddField(
            model_name='module',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='modules/pdfs/', verbose_name='PDF-файл'),
        ),
        migrations.AddField(
            model_name='module',
            name='test_questions',
            field=models.JSONField(blank=True, default=list, verbose_name='Вопросы для теста'),
        ),
        migrations.AddField(
            model_name='module',
            name='video_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на видео'),
        ),
        migrations.CreateModel(
            name='ModuleComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='myapp.module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Комментарий к модулю',
                'verbose_name_plural': 'Комментарии к модулям',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватарка')),
                ('bio', models.TextField(blank=True, verbose_name='О себе')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Город')),
                ('website', models.URLField(blank=True, verbose_name='Сайт')),
                ('telegram', models.CharField(blank=True, max_length=100, verbose_name='Telegram')),
                ('notifications_enabled', models.BooleanField(default=True, verbose_name='Уведомления')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_by', to='myapp.module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'module')},
            },
        ),
    ]
