# Generated by Django 6.0.7 on 2026-08-30 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_module_allow_comments_module_pdf_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='associations',
            field=models.JSONField(blank=True, default=list, verbose_name='Ассоциации'),
        ),
        migrations.AlterField(
            model_name='module',
            name='key_concepts',
            field=models.JSONField(blank=True, default=list, verbose_name='Ключевые понятия'),
        ),
        migrations.CreateModel(
            name='MindMapNodePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=100, verbose_name='ID узла')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mindmap_positions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Позиция узла карты',
                'verbose_name_plural': 'Позиции узлов карты',
                'unique_together': {('user', 'node_id')},
            },
        ),
    ]
