# Generated by Django 5.2.17 on 2026-08-31 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_alter_module_associations_alter_module_key_concepts_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Observation",
        ),
    ]
